site_name: TripGo Developer
site_author: SkedGo Pty Ltd
pages:
- Home: index.md
- Advanced: advanced.md
- Bookings:
  - Overview: bookings/overview.md
  - Android SDK: bookings/android.md
  - iOS SDK: bookings/ios.md
- Push Notifications: push.md
repo_url: https://github.com/skedgo/tripgo-api
# theme: readthedocs
