site_name: TripGo Developer
site_author: SkedGo Pty Ltd
pages:
- Getting Started: index.md
# - Specs: https://skedgo.github.io/tripgo-api/
- F.A.Q.: faq.md
# - Guides:
#   - SDKs: guides/sdks.md
- Extensions: extensions.md
- Enterprise:
  - Push Notifications: enterprise/push.md
  - Bookings (API): enterprise/bookings-api.md
  - Bookings (iOS): enterprise/bookings-ios.md
repo_url: https://github.com/skedgo/tripgo-api
# theme: readthedocs
google_analytics: ['UA-33335816-3', 'developer.tripgo.com']
