swagger: '2.0'
info:
  version: 1.0.0
  title: Push Notifications
  description: Endpoint for push notifications, there are two groups of endpoints

      - adding/removing devices to a specific user

      - push notification per device (testing) or userids.
basePath: /api
tags:
  - name: User
    description: update user profile data
  - name: Push
    description: send push notifications


paths:
  /user/push:
    get:
      tags:
        - User
      summary: get the list of devices registered
      description: return the list of devices registered for the given user
      consumes:
        - application/json
      parameters:
        - name: userToken
          in: header
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/json_pn_result'
          description: Success
        '401':
          schema:
            $ref: '#/definitions/json_error_message'
          description: Missing or invalid userToken
        default:
          description: Unexpected error.
    post:
      tags:
        - User
      summary: add push notification token to user
      description: Add/update a device/platform specific token for push notifications, note that you need to send a per user unique `deviceId`. We will only keep one token per (user,deviceid)
      consumes:
        - application/json
      parameters:
        - name: userToken
          in: header
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/json_push_token'
          description: push notification data
      responses:
        '200':
          schema:
            type: object
          description: Success
        '204':
          schema:
            type: object
          description: No change saved
        '401':
          schema:
            $ref: '#/definitions/json_error_message'
          description: Missing or invalid userToken
        default:
          description: Unexpected error.
    delete:
      tags:
        - User
      summary: remove a device token for push notifications
      description: Remove a device/platform specific token for push notifications.
      parameters:
        - name: userToken
          in: header
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/json_push_device'
          description: push notification device data
      responses:
        '200':
          schema:
            type: object
          description: Success
        '204':
          schema:
            type: object
          description: No change saved
        '401':
          schema:
            $ref: '#/definitions/json_error_message'
          description: Missing or invalid userToken
        default:
          description: Unexpected error.
  /push:
    post:
      tags:
        - Push
      summary: send push notification to users
      description: send a push notification to the registered devices of the given list of users
      consumes:
        - application/json
      parameters:
        - name: userID
          in: query
          type: string
          description: list of userIDs to send the message to
        - name: body
          in: body
          schema:
            $ref: '#/definitions/json_unified_message'
          description: push notification message
      responses:
        '200':
          schema:
            type: object
          description: push notification sent.
        '204':
          schema:
            type: object
          description: No notification sent, the selected users do not have PN devices registered.
        '401':
          schema:
            $ref: '#/definitions/json_error_message'
          description: Not allowed access, probably due to using an IP address not whitelisted
        default:
          description: Unexpected error.
  /push/android/{token}:
    post:
      tags:
        - Push
      summary: send push notification to Android (for dev/testing)
      description: send a push notification to the Android device of the specified token
      consumes:
        - application/json
      parameters:
        - name: token
          in: path
          required: true
          type: string
          description: token of the android device
        - name: body
          in: body
          schema:
            $ref: '#/definitions/json_unified_message'
          description: push notification message
      responses:
        '200':
          schema:
            type: object
          description: Success
        default:
          description: Unexpected error.
  /push/ios/{token}:
    post:
      tags:
        - Push
      summary: send push notification to iOS (for dev/testing)
      description: send a push notification to the iOS device of the specified token
      consumes:
        - application/json
      parameters:
        - name: token
          in: path
          required: true
          type: string
          description: token of the iOS device
        - name: body
          in: body
          schema:
            $ref: '#/definitions/json_unified_message'
          description: push notification message
      responses:
        '200':
          schema:
            type: object
          description: Success
        default:
          description: Unexpected error.
definitions:
  json_push_device:
    type: object
    title: Push Notification Platform/Device pair
    properties:
      platform:
        type: string
        enum:
          - android
          - ios
        description: android or ios device
      deviceId:
        type: string
        description: a unique id for that user/device pair
  json_push_token:
    type: object
    title: Push Notification Token for a specific Platform/Device pair
    allOf:
      - $ref: '#/definitions/json_push_device'
      - properties:
          token:
            type: string
  json_unified_message:
    type: object
    title: Push Notification Message
    properties:
      message:
        type: string
        description: notification message
      sound:
        type: string
        description: sound
      badge:
        type: integer
        description: badge
      ttl:
        type: integer
        description: time to live for the notification
  json_pn_result:
    type: object
    title: Response object including the list of PN tokens for each device of the user.
    properties:
      result:
        type: array
        items:
          - $ref: '#/definitions/json_push_token'
    example:
      result:
        - platform: "android"
          deviceId: "clkjwerds.fswersd"
          token: "sldfjsidls:mcvsadijfsad.fasldfjasdlfiasdjfskdf"
        - platform: "ios"
          deviceId: "asdfsdfs.fdwersfd"
          token: "234dsf345:dsfer.e42df234wfe23ro8279e8f2iu3984729ud"
  json_error_message:
    type: object
    title: Error Message
    properties:
      error:
        type: string
        description: error message
      errorCode:
        type: integer
        description: error code
      usererror:
        type: boolean
        description: whether it is a error to be shown to the user or not
