swagger: '2.0'
info:
  description: |-
    Data/Users Sync using REST<br><br>
            This API is deployed in http://db.skedgo.com and http://db2.xerox.skedgo.com.<br>
            It is also deployed in http://baryogenesis.skedgo.com/tripgodata-beta for testing purposes.<br>
            You should access to this endpoint using satapp deploys. For example:<br><br>
            http://tripgo.skedgo.com/satapp/api<br><br>
            SatApp will redirect the request to the appropriate database given the Region Eligibility:<br><br>
            'production' will use http://db.skedgo.com<br>
            'xum' 'xum-la'or 'xum-denver' will use http://db2.xerox.skedgo.com<br>
            'beta' will use http://bigbang.skedgo.com/tripgodata-beta<br>
  version: 1.0.0
  title: User Data
basePath: /api
tags:
  - name: User
    description: Endpoint for saving and retrieving user profile data
  - name: Trip
    description: Endpoint for saving and retrieving trips in JSON format
  - name: Vehicles
    description: Endpoint for saving and retrieving Vehicles
  - name: Favorites
    description: Endpoint for saving and retrieving Favorites
  - name: AppData
    description: >-
      This endpoint will allow to get and save the App data of the users. <br>

      It should be filtered by IP when enabled on production, as it currently
      does not have any access restriction
  - name: EventsInfo
    description: Endpoint for saving and retrieving EventsInfo
  - name: Habituals
    description: Endpoint for saving and retrieving Habituals
  - name: History
    description: Endpoint for saving and retrieving history search items
  - name: LocationKeys
    description: Endpoint for saving and retrieving Location Keys
  - name: TripItem
    description: Endpoint for saving and retrieving Trip Items
paths:
  /appdata/full:
    $ref: "./modules/user.paths.yaml#/appdata-full"
  /appdata/me:
    $ref: "./modules/user.paths.yaml#/appdata-me"
  '/appdata/latestuserIDs/{timestamp}':
    $ref: "./modules/user.paths.yaml#/appdata-latestuserIDs-{timestamp}"
  /appdata:
    $ref: "./modules/user.paths.yaml#/appdata"
  /appdata/userIDs:
    $ref: "./modules/user.paths.yaml#/appdata-userIDs"
  '/eventinfo/{id}':
    $ref: "./modules/user.paths.yaml#/eventinfo-{id}"
  /eventinfo/array:
    $ref: "./modules/user.paths.yaml#/eventinfo-array"
  /eventinfo:
    $ref: "./modules/user.paths.yaml#/eventinfo"
  '/favorite/{id}':
    $ref: "./modules/user.paths.yaml#/favorite-{id}"
  /favorite:
    $ref: "./modules/user.paths.yaml#/favorite"
  /favorite/array:
    $ref: "./modules/user.paths.yaml#/favorite-array"
  '/habitual/{id}':
    $ref: "./modules/user.paths.yaml#/habitual-{id}"
  /habitual:
    $ref: "./modules/user.paths.yaml#/habitual"
  /habitual/array:
    $ref: "./modules/user.paths.yaml#/habitual-array"
  /history:
    $ref: "./modules/user.paths.yaml#/history"
  /history/array:
    $ref: "./modules/user.paths.yaml#/history-array"
  /locationkey/array:
    $ref: "./modules/user.paths.yaml#/locationkey-array"
  '/locationkey/{id}':
    $ref: "./modules/user.paths.yaml#/locationkey-{id}"
  /locationkey:
    $ref: "./modules/user.paths.yaml#/locationkey"
  /tripitem:
    $ref: "./modules/user.paths.yaml#/tripitem"
  '/tripitem/{id}':
    $ref: "./modules/user.paths.yaml#/tripitem-{id}"
  /tripitem/array:
    $ref: "./modules/user.paths.yaml#/tripitem-array"
  /trip:
    $ref: "./modules/user.paths.yaml#/trip"
  '/trip/{id}':
    $ref: "./modules/user.paths.yaml#/trip-{id}"
  /user:
    $ref: "./modules/user.paths.yaml#/user"
  /user/phone:
    $ref: "./modules/user.paths.yaml#/user-phone"
  '/user/phone/{id}':
    $ref: "./modules/user.paths.yaml#/user-phone-{id}"
  '/user/phone/validate/{userID}/{phoneID}':
    $ref: "./modules/user.paths.yaml#/user-phone-validate-{userID}-{phoneID}"
  /user/image:
    $ref: "./modules/user.paths.yaml#/user-image"
  '/user/image/large/{userID}':
    $ref: "./modules/user.paths.yaml#/user-image-large-{userID}"
  '/user/image/small/{userID}':
    $ref: "./modules/user.paths.yaml#/user-image-small-{userID}"
  '/vehicle/{id}':
    $ref: "./modules/user.paths.yaml#/vehicle-{id}"
  /vehicle/array:
    $ref: "./modules/user.paths.yaml#/vehicle-array"
  /vehicle:
    $ref: "./modules/user.paths.yaml#/vehicle"
