swagger: "2.0"
info:
  version: 1.11.0
  title: TripGo
  x-logo:
    url: "https://developer.tripgo.com/img/tripgo-api-logo-color.svg"
  description:
    The TripGo API allows you to plan door-to-door trips using
    a large variety of public and private transport. It integrates real-time
    information and, for selected providers, allows users to book and pay
    for transport.<br/>
    <br/>
    This API is optimised to return a large number of trip results while
    maintaining a small package sizes. This has a number of complications.
    Notably, to get a trip's segments you need to combine the segment
    references with the segment templates.

  termsOfService: http://skedgo.com/api/terms
  contact:
    name: SkedGo API Team
    email: api@skedgo.com
    url: "https://developer.tripgo.com/"
  license:
    name: Apache License 2.0
    url: "https://github.com/skedgo/tripgo-api/blob/gh-pages/LICENSE"
host: api.tripgo.com
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  api_key:
    name: X-TripGo-Key
    type: apiKey
    in: header
security:
  - api_key: []
tags:
  - name: Configuration
  - name: Routing
  - name: Trips
  - name: TTP
  - name: Geocode
  - name: Locations
  - name: Stops
  - name: Services
  - name: Alerts

paths:
  /regions.json:
    post:
      tags:
        - Configuration
      summary: Available regions with host names per region.
      description:
        Lists available regions, their server host names and available
        transport modes. Provide optional hash code to only return output
        if the data has changed.
      parameters:
        - name: input
          in: body
          schema:
            $ref: '#/definitions/RegionsInput'
      responses:
        200:
          description: Available regions and modes
          schema:
            $ref: '#/definitions/RegionsResponse'


definitions:
  RegionsInput:
    type: object
    properties:
      v:
        type: number
        format: int32
        description: Version number
        minimum: 2
        maximum: 2
        multipleOf: 1
      hashCode:
        type: integer
        description: Hash code of your last response. If this is supplied the response might only consist of the hashCode and no other content, if the data has not changed.
    required:
      - v
    example:
      v: 2

  RegionsResponse:
    properties:
      hashCode:
        type: integer
        description: Hash code of the content of the response. You can pass this as an input parameter, if you only want to get content in the response if the data has changed.
      modes:
        type: object
        properties:
          $modeIdentifier:
            type: object
            description: This is a map/dictionary with multiple items of this type. Each key is a mode identifier. See https://developer.tripgo.com/faq/#mode-identifiers.
            properties:
              title:
                type: string
              URL:
                type: string
              icon:
                type: string
                description: File name part for downloading an image for this mode. [See separate documentation](TODO) for how to construct a URL from this.
              implies:
                type: string
                description: Another mode identifier that is required by this one, e.g., you can't request only school buses without also requesting regular public transport.
            required:
              - title

